# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c62ae1012dd33b9b1e52a54c776bab9832836cd51aa4931542af0d233d425a99c80d79f091c90e890d1f24c64a2e283d9f395e7d2c7a02ebd5156719e9d9ad6a

test:
  secret_key_base: ca4bf67efac67cf5b11919e73531bd7611b59aeae2ab0dc163908c1b57f21b096d434024a671c8b2a312761b9da804ab471df9ee59db5565ae621675fdc0fef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
